project:
  type: website

website:
  title: "MIBE SQL Corner"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Class materials"
        menu:
        - Introduction.qmd
        - 1-single-entity.qmd
        - 2-one-to-many.qmd
        - 3-many-to-many.qmd
        - 4-server-conn.qmd
        - 5-one-to-one-and-recursive.qmd
        - 6-many-to-many-recursive.qmd
        - 7-modelling-recap.qmd
      - text: "Class materials - complete"
        menu:
        - 1-single-entity-complete.qmd
        - 2-one-to-many-complete.qmd
        - 3-many-to-many-complete.qmd
        - 4-server-conn.qmd
        - 5-one-to-one-and-recursive-complete.qmd
        - 6-many-to-many-recursive-complete.qmd
        - 7-modelling-recap-complete.qmd
      - text: "Homeworks"
        menu:
        - Homework1.qmd
        - Homework2.qmd
        - Homework3.qmd
        - Homework4.qmd
        - Homework5.qmd
        - Homework6.qmd
      - text: "Homework solutions"
        menu:
        - Homework1-solution.qmd
        - Homework2-solution.qmd
        - Homework3-solution.qmd
        - Homework4-solution.qmd
        - Homework5-solution.qmd
        - Homework6-solution.qmd
      - text: "Challenges"
        menu:
        - 4-server-challenge.qmd
        - cdlibrary.qmd
        - cdlibrary-solution.qmd
      - text: "Readings"
        menu:
        - Readings.qmd
#  drafts:
#    - cdlibrary-solution.qmd
#  draft-mode: gone
        
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

