project:
  type: website

website:
  title: "MIBE SQL Corner"
  drafts:
    - 2-one-to-many.qmd
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Class materials"
        menu:
        - Introduction.qmd
        - 1-single-entity.qmd
      - text: "Homeworks"
        menu:
        - Homework1.qmd
      - text: "Homework solutions"
      - text: "Readings"
        menu:
        - Readings.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

